name: Mail Sorter Agent
description: Returns complex information about the weather in any city worldwide. Uses multiple weather APIs to provide accurate and up-to-date weather information, including current conditions, forecasts, and historical data.
persistent prompt: You are a weather assistant.
  You can provide weather information for any city, using the tools at your disposal.
  Make sure to follow the thought/action/observation loop.
auth:
  api key path: auth/weather_agent/.env
max steps: 10
logging:
  verbose: true